# Generated by Django 5.1 on 2026-06-07 06:29

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("ADMIN", "Admin"), ("USER", "Department User")],
                        default="USER",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="tpm.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PillarEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pillar",
                    models.CharField(
                        choices=[
                            ("KK", "Kobetsu Kaizen"),
                            ("JH", "Jishu Hozen"),
                            ("PM", "Planned Maintenance"),
                            ("QM", "Quality Maintenance"),
                            ("ET", "Education & Training"),
                            ("DM", "Design & Management"),
                            ("SHE", "Safety Health Environment"),
                            ("OTPM", "Office TPM"),
                        ],
                        max_length=10,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "data_entry_type",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("WEEKLY", "Weekly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_entries",
                        to="tpm.department",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pillar Entries",
                "unique_together": {("department", "pillar", "month", "year")},
            },
        ),
        migrations.CreateModel(
            name="Workstation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("leader", models.CharField(max_length=100)),
                ("inception_date", models.DateField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workstations",
                        to="tpm.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkstationKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kpi_name", models.CharField(max_length=200)),
                ("uom", models.CharField(max_length=50)),
                (
                    "goodness_indicator",
                    models.CharField(
                        choices=[
                            ("HIGHER", "Higher is Better ↑"),
                            ("LOWER", "Lower is Better ↓"),
                        ],
                        default="HIGHER",
                        max_length=10,
                    ),
                ),
                ("baseline", models.FloatField(blank=True, null=True)),
                ("commitment", models.FloatField(blank=True, null=True)),
                (
                    "workstation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="tpm.workstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KPIValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_no", models.CharField(max_length=10)),
                ("kpi_name", models.CharField(max_length=300)),
                ("uom", models.CharField(blank=True, max_length=50)),
                ("benchmark", models.FloatField(blank=True, null=True)),
                ("target", models.FloatField(blank=True, null=True)),
                ("actual", models.FloatField(blank=True, null=True)),
                ("availability", models.FloatField(blank=True, null=True)),
                ("performance", models.FloatField(blank=True, null=True)),
                ("quality", models.FloatField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "pillar_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpi_values",
                        to="tpm.pillarentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Value",
                "verbose_name_plural": "KPI Values",
                "unique_together": {("pillar_entry", "sl_no")},
            },
        ),
        migrations.CreateModel(
            name="WorkstationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("actual", models.FloatField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "workstation_kpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_values",
                        to="tpm.workstationkpi",
                    ),
                ),
            ],
            options={
                "unique_together": {("workstation_kpi", "month", "year")},
            },
        ),
    ]
