# tpm/utils/kpi_definitions.py

KPI_DEFINITIONS = {
    'KK': [
        {'sl_no': '1',  'name': 'Overall equipment efficiency-OEE(%)', 'uom': '%',
         'benchmark': 80.0, 'target': 90.0, 'is_oee_row': True},
        {'sl_no': '2',  'name': 'Productivity (Ton/Man or MWh/Man) (considering Company Employee only)', 'uom': 'Ton/Man',
         'benchmark': 480.0, 'target': 460.0},
        {'sl_no': '5',  'name': 'Total losses [Updation of Loss Tree] (Hrs.)', 'uom': 'Hrs',
         'benchmark': 250.0, 'target': 0.0},
        {'sl_no': '6',  'name': 'Kobetsu Kaizen registered (Nos.)', 'uom': 'Nos',
         'benchmark': 3.0, 'target': 3.0},
        {'sl_no': '7',  'name': 'Kobetsu Kaizen completed (Nos.)', 'uom': 'Nos',
         'benchmark': 3.0, 'target': 3.0},
        {'sl_no': '8',  'name': 'Total Saving through Kaizen (Rs.)', 'uom': 'Rs',
         'benchmark': 500000.0, 'target': 200000.0},
        {'sl_no': '10', 'name': 'Training on KK to improve the performance (Man Hours)', 'uom': 'Man Hours',
         'benchmark': 10.0, 'target': 20.0},
    ],
    'JH': [
        {'sl_no': '1',   'name': 'Compliance of JH Steps as per JH Master Plan (% [Actual/Planned])', 'uom': '%',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '2',   'name': 'White Fuguai Identified (Nos./month)', 'uom': 'Nos/month',
         'benchmark': 1200.0, 'target': 1200.0},
        {'sl_no': '3',   'name': 'White Fuguai Rectified (Nos./month)', 'uom': 'Nos/month',
         'benchmark': 1200.0, 'target': 1200.0},
        {'sl_no': '4',   'name': 'Red Fuguai Identified (Nos./month)', 'uom': 'Nos/month',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '5',   'name': 'Red Fuguai Rectified (Nos./month)', 'uom': 'Nos/month',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '6',   'name': 'JH Kaizen Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 50.0, 'target': 50.0},
        {'sl_no': '7',   'name': 'OPL Developed (Nos.)', 'uom': 'Nos',
         'benchmark': 50.0, 'target': 50.0},
        {'sl_no': '8A',  'name': 'Rank A machine with JH Step 1 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '8B',  'name': 'Rank A machine with JH Step 2 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '8C',  'name': 'Rank A machine with JH Step 3 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '9A',  'name': 'Rank B machine with JH Step 1 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '9B',  'name': 'Rank B machine with JH Step 2 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '9C',  'name': 'Rank B machine with JH Step 3 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '10A', 'name': 'Rank C machine with JH Step 1 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '10B', 'name': 'Rank C machine with JH Step 2 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '10C', 'name': 'Rank C machine with JH Step 3 Completed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '11',  'name': 'Training on JH to improve the performance (Man hours)', 'uom': 'Man hours',
         'benchmark': 100.0, 'target': 100.0},
    ],
    'PM': [
        {'sl_no': '1',  'name': 'Total breakdown nos. (Rank A + B + C machine)', 'uom': 'Nos',
         'benchmark': 25.0, 'target': 0.0},
        {'sl_no': '2',  'name': 'Total breakdown hours (Rank A + B + C machine)', 'uom': 'Hrs',
         'benchmark': 30.0, 'target': 0.0},
        {'sl_no': '3',  'name': 'No. of Machine with Repetitive breakdown (Nos./month)', 'uom': 'Nos/month',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '4',  'name': 'MTTR (Hours)', 'uom': 'Hrs',
         'benchmark': 1.15, 'target': 0.0},
        {'sl_no': '5',  'name': 'MTBF (Hours)', 'uom': 'Hrs',
         'benchmark': 48.08, 'target': 60.0},
        {'sl_no': '8',  'name': 'Equipment Availability (%)', 'uom': '%',
         'benchmark': 92.0, 'target': 100.0},
        {'sl_no': '9',  'name': 'CAPA Made (Nos.)', 'uom': 'Nos',
         'benchmark': 6.0, 'target': 5.0},
        {'sl_no': '10', 'name': 'PM Kaizen done (Nos.)', 'uom': 'Nos',
         'benchmark': 2.0, 'target': 2.0},
        {'sl_no': '11', 'name': 'One point Lesson (Nos.)', 'uom': 'Nos',
         'benchmark': 2.0, 'target': 2.0},
        {'sl_no': '13', 'name': 'Shutdown Maintenance rate (%)', 'uom': '%',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '14', 'name': 'PM Schedule compliance [as per SAP] (%)', 'uom': '%',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '15', 'name': 'Training on PM to improve the performance (Man hours)', 'uom': 'Man hours',
         'benchmark': 75.0, 'target': 30.0},
        {'sl_no': '16', 'name': 'Number of Breakdowns >= 30 minutes (nos.)', 'uom': 'Nos',
         'benchmark': 5.0, 'target': 0.0},
    ],
    'QM': [
        {'sl_no': '1A', 'name': 'Customer complaint (Matric T/Dispatched Qty.), %', 'uom': '%',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '1B', 'name': 'Response time to customer against complaint (Days)', 'uom': 'Days',
         'benchmark': 7.0, 'target': 5.0},
        {'sl_no': '2',  'name': 'Rejection (%)', 'uom': '%',
         'benchmark': 1.5, 'target': 1.0},
        {'sl_no': '3',  'name': 'Rework (%)', 'uom': '%',
         'benchmark': 2.0, 'target': 1.5},
        {'sl_no': '4',  'name': 'QM Kaizen/Project taken (Nos.)', 'uom': 'Nos',
         'benchmark': 3.0, 'target': 3.0},
        {'sl_no': '5',  'name': 'QA Matrix developed (Nos.)', 'uom': 'Nos',
         'benchmark': 1.0, 'target': 1.0},
        {'sl_no': '6',  'name': 'Training on QM to improve the performance (Man hours)', 'uom': 'Man hours',
         'benchmark': 10.0, 'target': 10.0},
    ],
    'ET': [
        {'sl_no': '1',  'name': 'Compliance of Skill evaluation of employees (%)', 'uom': '%',
         'benchmark': 97.0, 'target': 100.0},
        {'sl_no': '2',  'name': 'Trainings (Depts. Classroom) during the month (Nos. Actual/Planned)', 'uom': 'Nos',
         'benchmark': 13.0, 'target': 4.0},
        {'sl_no': '3',  'name': 'Employees covered (Depts. Classroom) during the month (%)', 'uom': '%',
         'benchmark': 80.0, 'target': 100.0},
        {'sl_no': '4',  'name': 'Training Man-hours (Man hrs./Emp.)', 'uom': 'Man hrs/Emp',
         'benchmark': 0.8, 'target': 1.0},
        {'sl_no': '5',  'name': 'On-The-Job Training during the month (Nos.)', 'uom': 'Nos',
         'benchmark': 10.0, 'target': 1.0},
        {'sl_no': '6',  'name': 'Employees covered (On the job) during the month (%)', 'uom': '%',
         'benchmark': 25.0, 'target': 20.0},
        {'sl_no': '7',  'name': "OPL's developed during the month (Including all Pillar) (Nos.)", 'uom': 'Nos',
         'benchmark': 1.0, 'target': 1.0},
        {'sl_no': '8A', 'name': 'Multi skilled Manpower_Uni-athlete (%)', 'uom': '%',
         'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '8B', 'name': 'Multi skilled Manpower_Bi-athlete (%)', 'uom': '%',
         'benchmark': 92.0, 'target': 80.0},
        {'sl_no': '8C', 'name': 'Multi skilled Manpower_Tri-athlete (%)', 'uom': '%',
         'benchmark': 60.0, 'target': 60.0},
        {'sl_no': '9',  'name': 'Skill Gap of Employee (0-5) (Score)', 'uom': 'Score',
         'benchmark': 2.0, 'target': 2.0},
        {'sl_no': '10', 'name': 'In-house trainers developed (Annual) (Nos.)', 'uom': 'Nos',
         'benchmark': 4.0, 'target': 2.0},
        {'sl_no': '11', 'name': 'Training on E&T to improve the performance (quarterly) (Nos.)', 'uom': 'Nos',
         'benchmark': 1.0, 'target': 1.0},
    ],
    'DM': [
        {'sl_no': '1', 'name': 'Sales from upgraded & New products over total sales (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '2', 'name': 'New product developments (Percentage)', 'uom': '%',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '3', 'name': 'Design related complaints/failures (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '4', 'name': 'New equipment/process developed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '5', 'name': 'Modification done in existing equipment/processes (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '6', 'name': 'Number of MP Sheet Developed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '7', 'name': 'Number of LCC Sheet Developed (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '8', 'name': 'Training on DM to improve the performance (Nos.)', 'uom': 'Nos',
         'benchmark': 0.0, 'target': 0.0},
    ],
    'SHE': [
        {'sl_no': '1A', 'name': 'Safety Observations made (Nos.)', 'uom': 'Nos', 'benchmark': 50.0, 'target': 50.0},
        {'sl_no': '1B', 'name': 'Safety Observations rectified (Nos.)', 'uom': 'Nos', 'benchmark': 50.0, 'target': 50.0},
        {'sl_no': '1C', 'name': 'Number of Near Misses Reported (Nos.)', 'uom': 'Nos', 'benchmark': 5.0, 'target': 5.0},
        {'sl_no': '2A', 'name': 'Numbers of Fatal accidents (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '2B', 'name': 'Numbers of reportable accidents (LTI) (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '2C', 'name': 'Numbers of MTI & First Aid Cases (Nos.)', 'uom': 'Nos', 'benchmark': 2.0, 'target': 0.0},
        {'sl_no': '3A', 'name': 'Employee (below executive) health check-up compliance adherence (%), monthly', 'uom': '%', 'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '3B', 'name': 'Employee (executive & above) health check-up compliance adherence (%), Quarterly', 'uom': '%', 'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '3C', 'name': 'Electrical Energy consumed (MWH) in PCDs-Pollution Control Devices', 'uom': 'MWH', 'benchmark': 100.0, 'target': 80.0},
        {'sl_no': '4',  'name': 'Compliance of Monitoring of environment parameters (as per limits)', 'uom': '%', 'benchmark': 100.0, 'target': 100.0},
        {'sl_no': '5',  'name': 'Water Consumption (kL/Ton)', 'uom': 'kL/Ton', 'benchmark': 3.5, 'target': 3.0},
        {'sl_no': '6',  'name': 'Dust level monitoring at workplace (ug/M3)', 'uom': 'ug/M3', 'benchmark': 100.0, 'target': 80.0},
        {'sl_no': '7',  'name': 'Noise level monitoring (db)', 'uom': 'db', 'benchmark': 85.0, 'target': 80.0},
        {'sl_no': '8',  'name': 'Low Illuminated area identified (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '9',  'name': 'Low Illuminated area rectified (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '10', 'name': 'Dust level monitoring at stacks (mg/M3)', 'uom': 'mg/M3', 'benchmark': 50.0, 'target': 30.0},
        {'sl_no': '11', 'name': 'No. of Kaizen themes or improvement project taken for improvement in Safety (Nos.)', 'uom': 'Nos', 'benchmark': 2.0, 'target': 2.0},
        {'sl_no': '12', 'name': 'Training on SHE (Man hours)', 'uom': 'Man hours', 'benchmark': 20.0, 'target': 20.0},
    ],
    'OTPM': [
        {'sl_no': '1',  'name': 'Losses Identified in Office TPM process (Hours)', 'uom': 'Hours', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '2',  'name': 'Losses rectified in Office TPM process (Hours)', 'uom': 'Hours', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '3',  'name': 'No. of Kaizen themes/improvement project taken/registered for reduction in losses', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '4',  'name': 'No. of Kaizen themes/improvement project completed for reduction in losses', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '5',  'name': 'OPL/SOPs prepared and displayed (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '6',  'name': 'Fuguai identified (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '7',  'name': 'Fuguai rectified (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '8',  'name': 'Area/Store/Offices identified for 1S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '9',  'name': 'Area/Store/Offices completed for 1S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '10', 'name': 'Area/Store/Offices identified for 2S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '11', 'name': 'Area/Store/Offices completed for 2S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '12', 'name': 'Area/Store/Offices identified for 3S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '13', 'name': 'Area/Store/Offices completed for 3S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '14', 'name': 'Area/Store/Offices identified for 4S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '15', 'name': 'Area/Store/Offices completed for 4S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '16', 'name': 'Area/Store/Offices identified for 5S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '17', 'name': 'Area/Store/Offices completed for 5S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '18', 'name': 'Area (Contractors) identify for 1S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '19', 'name': 'Area (Contractors) completed for 1S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '20', 'name': 'Area (Contractors) identify for 2S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '21', 'name': 'Area (Contractors) completed for 2S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '22', 'name': 'Area (Contractors) identify for 3S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '23', 'name': 'Area (Contractors) completed for 3S (Nos.)', 'uom': 'Nos', 'benchmark': 0.0, 'target': 0.0},
        {'sl_no': '24', 'name': 'Training on OTPM to improve the performance (Man hours)', 'uom': 'Man hours', 'benchmark': 0.0, 'target': 0.0},
    ],
}
